version: 1.0.{build}
platform: x64
environment:
  PATH: C:\Program Files\Racket;%PATH%
build_script:
- ps: >-
    Invoke-WebRequest https://github.com/pauldalewilliams/chocolatey-comm-pkgs/raw/6417a13eaf08f5b1da64589b443da1b752818ab6/racket/racket.7.0.nupkg -OutFile racket.7.0.nupkg

    Invoke-WebRequest https://raw.githubusercontent.com/pauldalewilliams/chocolatey-comm-pkgs/6417a13eaf08f5b1da64589b443da1b752818ab6/racket/racket.nuspec -OutFile racket.nuspec

    choco install C:\projects\video\racket.7.0.nupkg

    raco pkg install --deps search-auto -n video
test_script:
- ps: '# raco test -p video'
